name: .NET Core

on:
  push:
    branches: [ master, dev, items ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.10
    - name: Build with dotnet
      run: dotnet build --configuration Release Shopkeeper/Shopkeeper/Shopkeeper.csproj
    - name: Test with dotnet
      run: dotnet test --no-restore --verbosity normal
