# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Github Pages

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2.1.4
      with:
        node-version: '12.x'
    - name: Build with npm
      run: |
        npm ci
        npm run build --if-present
    - name: Deploy using gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/mickelsonmichael/dota2quiz.git
        npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
