 #${{ secrets.ENVIRONMENT_NAME }}

name: Deploy to Amazon
on: 
  push:
    branches:
      - "GithubActions"
  
jobs:
  deploy:
    name: "Deploy to AWS"

    runs-on: ubuntu-latest

    steps:
    - name: AWS Elastic Beanstalk cli
      uses: hmanzur/actions-aws-eb@v1.0.0
      with:
        command: |
            status Dota2quiz-env
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-east-2"

