name: Deploy to Amazon
on: 
  push:
    branches:
      - "GithubActions"
  
jobs:
  deploy:
    name: "Deploy to AWS"

    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: aws --help | echof
